console.log(false == 0); //True
console.log(false === 0); //False
console.log("" == 0); //True 
console.log("" === 0); //False
console.log(false == ""); //True
console.log(false === ""); //False
console.log(null == undefined); //True
console.log(null === undefined); //False
console.log(NaN == null); //False
console.log(NaN == undefined); //False
console.log(NaN == NaN); //False